// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfI4W7E3C3Ibjcyik37C59xnRxjltwwxw',
    appId: '1:130781448810:web:625bbfa1c7fb3092ef1813',
    messagingSenderId: '130781448810',
    projectId: 'mindwell-bcb94',
    authDomain: 'mindwell-bcb94.firebaseapp.com',
    storageBucket: 'mindwell-bcb94.appspot.com',
    measurementId: 'G-J48N03C2SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUmvapCv8ut-5XCViCZm57lUTYOqws3o8',
    appId: '1:130781448810:android:43a204f6b276c1ceef1813',
    messagingSenderId: '130781448810',
    projectId: 'mindwell-bcb94',
    storageBucket: 'mindwell-bcb94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZJaKHoAidhmlw1ulKgoMsuFi0sKfcD3o',
    appId: '1:130781448810:ios:70d364a8cd472adcef1813',
    messagingSenderId: '130781448810',
    projectId: 'mindwell-bcb94',
    storageBucket: 'mindwell-bcb94.appspot.com',
    iosBundleId: 'com.example.mindwell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZJaKHoAidhmlw1ulKgoMsuFi0sKfcD3o',
    appId: '1:130781448810:ios:a26e8ff9a06a1b9def1813',
    messagingSenderId: '130781448810',
    projectId: 'mindwell-bcb94',
    storageBucket: 'mindwell-bcb94.appspot.com',
    iosBundleId: 'com.example.mindwell.RunnerTests',
  );
}
